### ISSUE TITLE
@media rules not working in openfl

### ISSUE THREAD

**Issue by ConfidantCommunications** [haxeui/component-examples#1]
Hi Ian,
I tried compiling the "responsive" example on my Mac using OpenFL. There was a small problem where I had to change line 3 of the main.xml to `<style source="/main.css" />`. Now that I have it finding the css file, it seems that the rules within media queries are breaking display, i.e. only a white screen appears. What should I do?
-Allan

**Comment by ianharrigan** [comment]
Hi Allan,

Are you using the `new-component-method` branch?

**Comment by ConfidantCommunications** [comment]
No, is that the recommended way?

**Comment by ianharrigan** [comment]
Yup, currently the new-component-method branch has a totally new CSS parser that is the only one that can handle media queries and css animations - master cant handle any of these things. At some point (quite soon im hoping) it will replace master - it also has ALOT of other things! :)

Cheers,
Ian

PS: note you will need to use the branch for both haxeui-core aswell as haxeui-openfl

**Comment by ConfidantCommunications** [comment]
Perfect, I will try that. Thanks for your assistance!

**Comment by ConfidantCommunications** [comment]
Works!
